command_table table[] = {
	{"mov", TWO_PARAMS , ALL_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"cmp", TWO_PARAMS , ALL_ADDRESSINGS_TYPES,  ALL_ADDRESSINGS_TYPES }
	{"add", TWO_PARAMS , ALL_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"sub", TWO_PARAMS , ALL_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"not", ONE_PARAM , NO_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"clr", ONE_PARAM , NO_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"lea", TWO_PARAMS , ONE_AND_TWO_TYPES, NO_IMMEDIATE  }
	{"inc", ONE_PARAM , NO_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"dec", ONE_PARAM , NO_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"jmp", LABEL_AND_TWO_PARAMS , NO_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"bne", LABEL_AND_TWO_PARAMS , NO_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"red", ONE_PARAM , NO_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"prn", ONE_PARAM , NO_ADDRESSINGS_TYPES,  ALL_ADDRESSINGS_TYPES  }
	{"jsr", LABEL_AND_TWO_PARAMS , NO_ADDRESSINGS_TYPES, NO_IMMEDIATE  }
	{"rts", NO_PARAMS , NO_ADDRESSINGS_TYPES, NO_ADDRESSINGS_TYPES  }
	{"stop", NO_PARAMS , NO_ADDRESSINGS_TYPES, NO_ADDRESSINGS_TYPES  }
}

