#include "table.h"
const command_table table[] = {
	{"mov", TWO_PARAMS , ALL_BUT_TWO, ONE_AND_THREE  },
	{"cmp", TWO_PARAMS , ALL_BUT_TWO,  ALL_BUT_TWO },
	{"add", TWO_PARAMS , ALL_BUT_TWO, ONE_AND_THREE  },
	{"sub", TWO_PARAMS , ALL_BUT_TWO, ONE_AND_THREE  },
	{"not", ONE_PARAM , NO_ADDRESSINGS_TYPES, ONE_AND_THREE  }, /*need fix: validation*/
	{"clr", ONE_PARAM , NO_ADDRESSINGS_TYPES, ONE_AND_THREE  },
	{"lea", TWO_PARAMS , ONLY_ONE, ONE_AND_THREE  },
	{"inc", ONE_PARAM , NO_ADDRESSINGS_TYPES, ONE_AND_THREE  },
	{"dec", ONE_PARAM , NO_ADDRESSINGS_TYPES, ONE_AND_THREE  },
	{"jmp", LABEL_NON_OR_TWO_PARAMS , NO_ADDRESSINGS_TYPES, ONE_AND_TWO  },
	{"bne", LABEL_NON_OR_TWO_PARAMS , NO_ADDRESSINGS_TYPES, ONE_AND_TWO  },
	{"red", ONE_PARAM , NO_ADDRESSINGS_TYPES, ONE_AND_THREE  },
	{"prn", ONE_PARAM , NO_ADDRESSINGS_TYPES,  ALL_BUT_TWO  },
	{"jsr", LABEL_NON_OR_TWO_PARAMS , NO_ADDRESSINGS_TYPES, ONE_AND_TWO  },
	{"rts", NO_PARAMS , NO_ADDRESSINGS_TYPES, NO_ADDRESSINGS_TYPES  },
	{"stop", NO_PARAMS , NO_ADDRESSINGS_TYPES, NO_ADDRESSINGS_TYPES  }
};

